//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace Learning
{
		public class RLNode
		{
			public int x;
			public int y;
			public int t;
				
			public RLNode xm1y;
			double xm1yQ;
			public RLNode xym1;
			double xym1Q;
			public RLNode xp1y;
			double xp1yQ;
			public RLNode xyp1;
			double xyp1Q;
			public RLNode xy;
			double xyQ;
			
				public RLNode ( int _x, int _y, int _t )
				{
					xm1y = null;
					xym1 = null;
					xp1y = null;
					xyp1 = null;
					xy = null;
					x = _x;
					y = _y;
					t = _t;
				}
				
		}
}

